
const AUTH_NOT_AUTHENTICATED = 'AUTH/NOT_AUTHENTICATED'
const AUTH_INVALID_TOKEN = 'AUTH/INVALID_TOKEN'
const AUTH_PERMISSION_DENIED = 'AUTH/PERMISSION_DENIED'
const AUTH_INVALID_PASSWORD = 'AUTH/INVALID_PASSWORD'

const COMMON_SERVER_ERROR = 'COMMON/SERVER_ERROR'
const COMMON_VALIDATION_ERROR = 'COMMON/VALIDATION_ERROR'

const USERS_USER_WITH_SAME_USERNAME_EXISTS = 'USERS/USER_WITH_SAME_USERNAME_EXISTS'
const USERS_USER_DOES_NOT_EXIST = 'USERS/USER_DOES_NOT_EXIST'
const USERS_ALREADY_FOLLOWING = 'USERS/ALREADY_FOLLOWING'
const USERS_NOT_FOLLOWING_YET = 'USERS/NOT_FOLLOWING_YET'

const POSTS_NOT_FOUND = 'POSTS/NOT_FOUND'
const POSTS_ALREADY_LIKED = 'POSTS/ALREADY_LIKED'
const POSTS_DID_NOT_LIKE_YET = 'POSTS/DID_NOT_LIKE_YET'
const POSTS_FORBIDDEN_TO_DELETE = 'POSTS/FORBIDDEN_TO_DELETE'

module.exports = {
  AUTH_INVALID_TOKEN,
  AUTH_NOT_AUTHENTICATED,
  COMMON_SERVER_ERROR,
  AUTH_PERMISSION_DENIED,
  USERS_USER_WITH_SAME_USERNAME_EXISTS,
  USERS_USER_DOES_NOT_EXIST,
  USERS_ALREADY_FOLLOWING,
  AUTH_INVALID_PASSWORD,
  COMMON_VALIDATION_ERROR,
  USERS_NOT_FOLLOWING_YET,
  POSTS_NOT_FOUND,
  POSTS_ALREADY_LIKED,
  POSTS_DID_NOT_LIKE_YET,
  POSTS_FORBIDDEN_TO_DELETE
}
