
const AUTH_NOT_AUTHENTICATED = 'AUTH/NOT_AUTHENTICATED'
const AUTH_INVALID_TOKEN = 'AUTH/INVALID_TOKEN'
const AUTH_PERMISSION_DENIED = 'AUTH/PERMISSION_DENIED'
const AUTH_INVALID_PASSWORD = 'AUTH/INVALID_PASSWORD'

const COMMON_SERVER_ERROR = 'COMMON/SERVER_ERROR'
const COMMON_VALIDATION_ERROR = 'COMMON/VALIDATION_ERROR'

const USERS_USER_WITH_SAME_USERNAME_EXISTS = 'USERS/USER_WITH_SAME_USERNAME_EXISTS'
const USERS_USER_DOES_NOT_EXIST = 'USERS/USER_DOES_NOT_EXIST'


module.exports = {
  AUTH_INVALID_TOKEN,
  AUTH_NOT_AUTHENTICATED,
  COMMON_SERVER_ERROR,
  AUTH_PERMISSION_DENIED,
  USERS_USER_WITH_SAME_USERNAME_EXISTS,
  USERS_USER_DOES_NOT_EXIST,
  AUTH_INVALID_PASSWORD,
  COMMON_VALIDATION_ERROR
}
